server:
  port: 8282

pizza:
  sauce: bbq
  topping: chicken
  crust: stuffed

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/tasktracker
    username: admin
    password: admin
    driver-class-name: org.mariadb.jdbc.Driver

  spring:
    jpa:
      show-sql: true
      ddl-auto: update
      open-in-view: true
    sql:
      init:
        mode: always