server:
  port: 8282

pizza:
  sauce: bbq
  topping: chicken
  crust: stuffed

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/database
    username: admin
    password: admin
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always